/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dlg_rites.java
 *
 * Created on Feb 13, 2012, 12:29:39 AM
 */
package bb.dlg2;

import java.util.logging.Level;
import javax.swing.text.AbstractDocument;
import overallPOS.modules.share.utils.CloseDialog;
import overallPOS.modules.share.utils.CurrencyDocument;

/**
 *
 * @author Dummy
 */
public class dlg_rites1 extends javax.swing.JDialog {

    //<editor-fold defaultstate="collapsed" desc=" callback ">
    private Callback callback;

    public void setCallback(Callback callback) {
        this.callback = callback;




    }

    

    public static interface Callback {

        void ok(CloseDialog closeDialog, Data data);
    }

    public static class Data {

        public final String name;
        public final double rate;
        public final String state;

        public Data(String name, double rate, String state) {
            this.name = name;
            this.rate = rate;
            this.state = state;
        }
    }
//</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" Constructors ">
    private dlg_rites1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    private dlg_rites1(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInit();
    }

    public dlg_rites1() {
        super();
        initComponents();
        myInit();

    }
    private dlg_rites1 myRef;

    private void setThisRef(dlg_rites1 myRef) {
        this.myRef = myRef;
    }
    private static java.util.Map<Object, dlg_rites1> dialogContainer = new java.util.HashMap();

    public static void clearUpFirst(java.awt.Window parent) {
        if (dialogContainer.containsKey(parent)) {
            dialogContainer.remove(parent);
        }
    }

    public static dlg_rites1 create(java.awt.Window parent, boolean modal) {

        if (modal) {
            return create(parent, ModalityType.APPLICATION_MODAL);
        }

        return create(parent, ModalityType.MODELESS);

    }

    public static dlg_rites1 create(java.awt.Window parent, java.awt.Dialog.ModalityType modalType) {

        if (parent instanceof java.awt.Frame) {

            dlg_rites1 dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new dlg_rites1((java.awt.Frame) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        if (parent instanceof java.awt.Dialog) {
            dlg_rites1 dialog = dialogContainer.get(parent);

            if (dialog == null) {
                dialog = new dlg_rites1((java.awt.Dialog) parent, false);
                dialog.setModalityType(modalType);
                dialogContainer.put(parent, dialog);
                java.util.logging.Logger.getAnonymousLogger().log(Level.INFO, "instances: {0}", dialogContainer.size());
                dialog.setThisRef(dialog);
                return dialog;
            } else {
                dialog.setModalityType(modalType);
                return dialog;
            }

        }

        return null;

    }
    //</editor-fold>    

    //<editor-fold defaultstate="collapsed" desc=" main ">
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }


        dlg_rites1 dialog = dlg_rites1.create(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc=" added ">
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
        if (visible == true) {
            getContentPane().removeAll();
            initComponents();
            myInit();
            repaint();
//            validateTree();
        }


    }

    public javax.swing.JPanel getSurface() {
        return (javax.swing.JPanel) getContentPane();
    }

    public void nullify() {
        myRef.setVisible(false);
        myRef = null;
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_rate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rb_ord = new javax.swing.JRadioButton();
        rb_special = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 55, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, -1));

        jButton2.setText("Cancel");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 130, 90, -1));
        jPanel2.add(tf_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 350, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Rate:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        jPanel2.add(tf_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 85, 32));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Type:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        rb_ord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_ord.setSelected(true);
        rb_ord.setText("Ordinary");
        jPanel2.add(rb_ord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        rb_special.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rb_special.setText("Special");
        jPanel2.add(rb_special, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 510, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        do_ok();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rb_ord;
    private javax.swing.JRadioButton rb_special;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_rate;
    // End of variables declaration//GEN-END:variables

    public void passs() {
      
      
    }
    private void myInit() {
//        tf_rate.setDocument(new CurrencyDocument(true, 100000));
    }

    public void pass(String aw) {
        if (aw.equals("1")) {
            rb_special.setVisible(false);
            rb_ord.setVisible(false);
            jLabel3.setVisible(false);
            rb_ord.setSelected(false);
            rb_special.setSelected(true);
        } else {
            rb_special.setVisible(false);
            rb_ord.setVisible(false);
            jLabel3.setVisible(false);
            rb_ord.setSelected(true);
            rb_special.setSelected(false);
        }

        if (aw.equals("3")) {
            rb_special.setVisible(false);
            rb_ord.setVisible(false);
            jLabel3.setVisible(false);
        }
    }

    private void do_ok() {

        String name = tf_name.getText();
        double rate = Double.parseDouble(tf_rate.getText());
        String stat = "";
        if (rb_ord.isSelected()) {
            stat = "Ordinary";
        }
        if (rb_special.isSelected()) {
            stat = "Special";
        }
        if (callback != null) {
            callback.ok(new CloseDialog(this), new Data(name, rate, stat));

        }
    }

    public void pass(String name, double rate, String stat) {
        System.out.println(rate);

        if (stat.equals("Ordinary")) {
        } else {
        }
        tf_name.setText(name);
        tf_rate.setText("" + rate);
//        tf_rate.setDocument(new CurrencyDocument(true, 100000));

    }
}
